development:
  adapter:  mysql2
  database: crb_development
  username: root
  password:

test:
  adapter: mysql2
  database: crb_test
  username: root
  password:

production:
  adapter: mysql2
  database: crb
  username: root
  password:
